/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_layoult`; params?: Router.UnknownInputParams; } | { pathname: `/datails`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/navigate-button`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/_layoult`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/feed/_layoult`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/feed`; params?: Router.UnknownInputParams; } | { pathname: `/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/tabs/feed/[postId]`, params: Router.UnknownInputParams & { postId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_layoult`; params?: Router.UnknownOutputParams; } | { pathname: `/datails`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/navigate-button`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/_layoult`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/feed/_layoult`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/feed`; params?: Router.UnknownOutputParams; } | { pathname: `/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/tabs/feed/[postId]`, params: Router.UnknownOutputParams & { postId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_layoult${`?${string}` | `#${string}` | ''}` | `/datails${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/navigate-button${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/tabs/_layoult${`?${string}` | `#${string}` | ''}` | `/tabs/perfil${`?${string}` | `#${string}` | ''}` | `/tabs/feed/_layoult${`?${string}` | `#${string}` | ''}` | `/tabs/feed${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_layoult`; params?: Router.UnknownInputParams; } | { pathname: `/datails`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/navigate-button`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/_layoult`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/feed/_layoult`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/feed`; params?: Router.UnknownInputParams; } | `/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/tabs/feed/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/tabs/feed/[postId]`, params: Router.UnknownInputParams & { postId: string | number; } };
    }
  }
}
